const GENERIC_STATUS_CODES = {
  NON_EXISTANT: "NON_EXISTANT",
  NOT_STARTED: "NOT_STARTED",
  RESERVED: "RESERVED",
  RESERVE_FAILED: "RESERVE_FAILED",
  PARTIALLY_CAPTURED: "PARTIALLY_CAPTURED",
  CAPTURED: "CAPTURED",
  INITIATED: "INITIATED",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  CANCELLED_CONFLICTING: "CANCELLED_CONFLICTING",
  CANCEL_REQUESTED: "CANCEL_REQUESTED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
  REJECTED: "REJECTED",
  TIMED_OUT_REJECT: "TIMED_OUT_REJECT",
  REFUNDED_PARTIAL: "REFUNDED_PARTIAL",
  REFUND_REQUESTED: "REFUND_REQUESTED",
};

module.exports = {
  GENERIC_STATUS_CODES,
};
